
SIZE_SQUARE = 50
SIZE_SNAKE = SIZE_SQUARE - 2
SIZE_APPLE = SIZE_SQUARE - 6

BOARD_SIZE = (15, 15)
SCREEN_WIDTH = ((SIZE_SQUARE + 1) * (BOARD_SIZE[0] + 1)) + 1
SCREEN_HEIGHT = ((SIZE_SQUARE + 1) * (BOARD_SIZE[1] + 1)) + 1

START_POS = (BOARD_SIZE[0] // 2 + 1, BOARD_SIZE[1] // 2 + 1)
START_LENGTH = 4
GROWTH = 3

GAME_SPEED = 4

COLOR_SNAKE = (0, 255, 0) # GREEN
COLOR_APPLE = (255, 0, 0) # RED