
SQUARE_SIZE = 20
BOARD_SIZE = 20
SCREEN_WIDTH = (SQUARE_SIZE * BOARD_SIZE) + 1
SCREEN_HEIGHT = (SQUARE_SIZE * BOARD_SIZE) + 1
START_POS_X = SCREEN_WIDTH // 2 + 1
START_POS_Y = SCREEN_HEIGHT // 2 + 1
START_LENGTH = 3
GAME_SPEED = 4